### ISSUE TITLE
Fails when downloading files over 1 MiB (Error: d.ts file must have a matching npm package)

### ISSUE THREAD

**Issue by andersk** [DefinitelyTyped/dts-critic#10]
Running `dts-critic` on certain packages like `webpack` results in this confusing error:

```console
$ node index.js ../DefinitelyTyped/types/webpack/index.d.ts 
/home/anders/js/dts-critic/index.js:113
                throw new Error(`d.ts file must have a matching npm package.
                ^

Error: d.ts file must have a matching npm package.
To resolve this error, either:
1. Change the name to match an npm package.
2. Add a Definitely Typed header with the first line


    // Type definitions for non-npm package webpack-browser

Add -browser to the end of your name to make sure it doesn't conflict with existing npm packages.

- OR -

3. Explicitly provide dts-critic with a source file. This is not allowed for submission to Definitely Typed.

    at findNames (/home/anders/js/dts-critic/index.js:113:23)
    at dtsCritic (/home/anders/js/dts-critic/index.js:26:19)
    at main (/home/anders/js/dts-critic/index.js:59:12)
    at Object.<anonymous> (/home/anders/js/dts-critic/index.js:39:5)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11
```

What actually happened here was that `dts-critic` tried to use `download-file-sync` to download https://registry.npmjs.org/webpack, and since `download-file-sync` doesn’t override the default `maxBuffer: 1048576` of `execFileSync`, it failed with `ENOBUFS`.

I sent a PR to vjeux/download-file-sync#7, though I’m not sure if that package is actively maintained. Either way, it’d be nice if `dts-critic` produced a less unhelpful error message on download failures.

**Comment by Jessidhia** [comment]
An example when running the exact command `dts-critic` is running:

```
> require('download-file-sync')('https://registry.npmjs.org/styled-components')
Thrown:
<ref *1> Error: spawnSync curl ENOBUFS
    at Object.spawnSync (internal/child_process.js:1047:20)
    at spawnSync (child_process.js:589:24)
    at Object.execFileSync (child_process.js:616:15)
    at module.exports (/Users/jessie/src/DefinitelyTyped/node_modules/download-file-sync/index.js:3:6) {
  errno: -55,
  code: 'ENOBUFS',
  syscall: 'spawnSync curl',
  path: 'curl',
  spawnargs: [ '--silent', '-L', 'https://registry.npmjs.org/styled-components' ],
  error: [Circular *1],
  status: null,
  signal: 'SIGTERM',
  output: [
    null,
    '(huge truncated string)',
    ''
  ],
  pid: 32551,
  stdout: '(huge truncated string)',
  stderr: ''
}
```

The pull request above was actually accepted but... not released.

It's a tiny package anyway so if you _really_ want to keep this executing synchronously, you could as well just inline the definition.

An alternative that is probably much better is to fetch the `/latest` endpoint, e.g. http://registry.npmjs.org/styled-components/latest, which is tiny enough. The top level endpoint returns every version that ever existed. Unfortunately the API doesn't seem to allow you to query for a range or for a partial version, must be exact.

**Comment by gabritto** [comment]
This issue doesn't seem to occur as of version 3.0 of dts-critic.
