### ISSUE TITLE
Mislabeled Error Thrown on retrieveNpmHomepageOrFail if cURL is not installed

### ISSUE THREAD

**Issue by carboneater** [DefinitelyTyped/dts-critic#3]
Steps to Reproduce:
- Run dts-critic on a package (failed every time in definitelyTyped for me) without cURL installed.  
(`$ sudo apt install curl` fixed it all for me)

Current Behavior:
- dts-critic throws 
```
Error(`d.ts file must have a matching npm package.
To resolve this error, either:
1. Change the name to match an npm package.
2. Add a Definitely Typed header with the first line


    // Type definitions for non-npm package ${dts}-browser

Add -browser to the end of your name to make sure it doesn't conflict with existing npm packages.

- OR -

3. Explicitly provide dts-critic with a source file. This is not allowed for submission to Definitely Typed.
```
Expected Behavior:
Running the `retrieveNpmHomepageOrFail` main command: `download('https://registry.npmjs.com/express-http-proxy')` results in the following error.
```js
{ Error: spawnSync curl ENOENT
    at Object.spawnSync (internal/child_process.js:990:20)
    at spawnSync (child_process.js:601:24)
    at Object.execFileSync (child_process.js:629:13)
    at module.exports (/opt/github/dtslint/node_modules/download-file-sync/index.js:3:6)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawnSync curl',
  path: 'curl',
  spawnargs:
   [ '--silent',
     '-L',
     'https://registry.npmjs.com/express-http-proxy' ],
  error: [Circular],
  status: null,
  signal: null,
  output: null,
  pid: 1344,
  stdout: null,
  stderr: null }
```
Throwing this error as is would actually be a lot more helpful.

**Comment by sandersn** [comment]
I believe this is fixed now.
